### ISSUE TITLE
Why does this package need to install google cloud auth, storage, api etc?

### ISSUE THREAD

**Issue by GiacomoCherry** [Pandora-Intelligence/crosslingual-coreference#11]
Hi,

after installing the library I saw google-api-core-2.10.1 google-auth-2.12.0 google-cloud-core-2.3.2 google-cloud-storage-1.44.0 have been installed as well. In fact these packages can be found in the poetry.lock file.

Is there a reason (I don't get) why this library needs these packages?

Thanks

**Comment by davidberenstein1957** [comment]
@GiacomoCherry  It needs those packages because it uses a custom-trained model hosted on our private Google cloud repo. So, in order to download it needs those packages.
