### ISSUE TITLE
Visualization code

### ISSUE THREAD

**Issue by saitej123** [Pandora-Intelligence/crosslingual-coreference#13]
Please add displacy module to visualise

**Comment by davidberenstein1957** [comment]
@saitej123 Cool you are enjoying the package. I will look into this tomorrow.

**Comment by davidberenstein1957** [comment]
Hello, sorry for the delay, but I added this just now. @saitej123 
https://github.com/Pandora-Intelligence/crosslingual-coreference#visualize-spacy-pipeline

**Comment by saitej123** [comment]
thanks !
