### ISSUE TITLE
How to cite this repository?

### ISSUE THREAD

**Issue by ritwikmishra** [Pandora-Intelligence/crosslingual-coreference#18]
Is there publication for this work?

**Comment by davidberenstein1957** [comment]
David, B. (2022). Crosslingual Coreference - a multi-lingual approach to AllenNLP CoReference Resolution along with a wrapper for spaCy. (Version 0.2.9) [Computer software]

**Comment by davidberenstein1957** [comment]
@software{David_Crosslingual_Coreference_-_2022,
author = {David, Berenstein},
month = {9},
title = {{Crosslingual Coreference - a multi-lingual approach to AllenNLP CoReference Resolution along with a wrapper for spaCy.}},
version = {0.2.9},
year = {2022}
}
