### ISSUE TITLE
crosslingual_coreference is not installing on VM , jsonnet is the package giving the error

### ISSUE THREAD

**Issue by 0121ishant** [Pandora-Intelligence/crosslingual-coreference#8]
![image](https://user-images.githubusercontent.com/58084123/180740794-289c3dab-3e69-4326-9165-02921cb70cc3.png)
![image](https://user-images.githubusercontent.com/58084123/180740868-87e5ef8e-adce-485b-87b4-1778870d48d0.png)

**Comment by davidberenstein1957** [comment]
This is an AllenNLP recurring issue. https://github.com/allenai/allennlp/issues/2779

**Comment by saitej123** [comment]
using this "apt-get -y install build-essential" worked for me
